// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180914123104_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Models.CredentialModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<int>("UserID");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("Database.Models.DialogModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("DialogModel");
                });

            modelBuilder.Entity("Database.Models.FriendshipModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendID");

                    b.Property<int>("MeID");

                    b.HasKey("ID");

                    b.HasIndex("FriendID");

                    b.HasIndex("MeID");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Database.Models.MessageModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID");

                    b.Property<string>("Content");

                    b.Property<int>("DialogID");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("DialogID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Database.Models.PostModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID");

                    b.Property<string>("Content");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Database.Models.UserDialogModel", b =>
                {
                    b.Property<int>("UserID");

                    b.Property<int>("DialogID");

                    b.HasKey("UserID", "DialogID");

                    b.HasIndex("DialogID");

                    b.ToTable("UserDialogModel");
                });

            modelBuilder.Entity("Database.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.Property<int>("Sex");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Database.Models.CredentialModel", b =>
                {
                    b.HasOne("Database.Models.UserModel", "User")
                        .WithOne("Credential")
                        .HasForeignKey("Database.Models.CredentialModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.FriendshipModel", b =>
                {
                    b.HasOne("Database.Models.UserModel", "Friend")
                        .WithMany("FriendOf")
                        .HasForeignKey("FriendID");

                    b.HasOne("Database.Models.UserModel", "Me")
                        .WithMany("Friends")
                        .HasForeignKey("MeID");
                });

            modelBuilder.Entity("Database.Models.MessageModel", b =>
                {
                    b.HasOne("Database.Models.UserModel", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.DialogModel", "Dialog")
                        .WithMany("Messages")
                        .HasForeignKey("DialogID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.PostModel", b =>
                {
                    b.HasOne("Database.Models.UserModel", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Database.Models.UserDialogModel", b =>
                {
                    b.HasOne("Database.Models.DialogModel", "Dialog")
                        .WithMany("DialogUsers")
                        .HasForeignKey("DialogID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Database.Models.UserModel", "User")
                        .WithMany("UserDialogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
